name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # execute gradle command for running API test
    - name: Execute API Testing
      run: ./gradlew api-testing

    # execute gradle command for running WEB test
    - name: Execute WEB Testing
      run: ./gradlew web-testing

    # upload artifacts
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: |
          reports/test-report-web.html
          reports/test-report-api.html
